ci:
  autoupdate_commit_msg: "MAINT: update pip constraints and pre-commit"
  autoupdate_schedule: quarterly
  skip:
    - prettier
    - taplo

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/ComPWA/repo-maintenance
    rev: 0.1.13a4
    hooks:
      - id: check-dev-files
        args:
          - --ignore-author
          - --no-github-actions
          - --no-gitpod
          - --no-prettierrc
          - --no-python
          - --no-ruff
          - --no-version-branches
          - --pin-requirements=quarterly
          - --repo-name=strong2020-salamanca
      - id: colab-toc-visible

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-flake8
      - id: nbqa-isort
      - id: nbqa-pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black-jupyter
        args: [--line-length=85]
        types_or: [jupyter]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.code_folding
            cell.metadata.id
            cell.metadata.pycharm
            cell.metadata.user_expressions
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector
            metadata.vscode

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.8.1
    hooks:
      - id: taplo

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place
