ci:
  autoupdate_commit_msg: "MAINT: update pip constraints and pre-commit"
  autoupdate_schedule: quarterly

  skip: []

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/ComPWA/policy
    rev: 0.4.1
    hooks:
      - id: check-dev-files
        args:
          - --dev-python-version=3.12
          - --no-github-actions
          - --no-prettierrc
          - --no-python
          - --no-ruff
          - --no-version-branches
          - --pin-requirements=quarterly
          - --repo-name=strong2020-salamanca
      - id: colab-toc-visible
      - id: remove-empty-tags

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          - --drop-empty-cells
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.code_folding
            cell.metadata.editable
            cell.metadata.id
            cell.metadata.pycharm
            cell.metadata.slideshow
            cell.metadata.user_expressions
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector
            metadata.vscode

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-flake8
      - id: nbqa-isort
      - id: nbqa-pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.3.3
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black-jupyter
        args: [--line-length=85]
        types_or: [jupyter]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
        exclude: >-
          (?x)^(
            .*\.py
          )$
