[project]
name = "lecture"
version = "0.1.0"
requires-python = "~=3.14.0"
dependencies = [
    "ampform>=0.14.8",
    "nbformat>=4.2.0",
    "numpy",
    "plotly",
    "sympy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "ANN00",
    "unused-method-argument",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "lambda-assignment",
    "FBT00",
    "TC00",
    "single-line-implicit-string-concatenation",
    "invalid-class-name",
    "non-lowercase-variable-in-function",
    "non-ascii-name",
    "too-many-arguments",
    "too-many-positional-arguments",
    "magic-value-comparison",
    "missing-f-string-syntax",
    "assert",
]
select = ["ALL"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.flake8-self]
ignore-names = ["_print"]

[tool.ruff.lint.pylint]
allow-dunder-method-names = ["_latex_repr_"]

[tool.uv.workspace]
