[project]
name = "lecture"
version = "0.1.0"
requires-python = "~=3.14.0"
dependencies = [
    "gdown",
    "matplotlib",
    "numpy",
    "pandas",
    "pylorentz",
    "scipy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-type-function-argument",
    "missing-return-type-undocumented-public-function",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "single-line-implicit-string-concatenation",
    "invalid-function-name",
    "invalid-argument-name",
    "mixed-case-variable-in-global-scope",
    "too-many-arguments",
    "too-many-positional-arguments",
    "print",
]
select = ["ALL"]

[tool.uv.workspace]
