[project]
name = "lecture"
version = "0.1.0"
requires-python = "~=3.14.0"
dependencies = [
    "gdown",
    "matplotlib",
    "numpy",
]

[tool.ruff]
preview = true

[tool.ruff.lint]
ignore = [
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D",
    "single-line-implicit-string-concatenation",
    "os-path-exists",
]
select = ["ALL"]

[tool.uv.workspace]
