title: Solutions to STRON2020 HaSP School
author: Participants of the STRONG2020 HaSP School
copyright: "2023"
logo: https://indico.ific.uv.es/event/6803/logo-2761386249.png

exclude_patterns:
  - .virtual_documents/*
  - lecture24_utilities.ipynb

execute:
  allow_errors: false
  execute_notebooks: cache
  timeout: 600

html:
  use_repository_button: true

launch_buttons:
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  notebook_interface: jupyterlab

only_build_toc_files: true

repository:
  url: https://github.com/ComPWA/strong2020-salamanca
  path_to_book: docs
  branch: main

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    nb_execution_show_tb: True
    suppress_warnings:
      - mystnb.unknown_mime_type
  extra_extensions:
    - sphinx_exercise
